const stops=[
["Start · Via Santa Maria della Fede",40.85823,14.26857,"Your accommodation. Start walking southwest toward Porta Capuana.","Start","","",""],
["Porta Capuana",40.85445,14.26539,"A dramatic medieval gateway marking the edge of the historic centre.","10–15 min","Why go","This is your first visual transition from the modern outskirts into old Naples. The dark stone towers and white marble arch make a surprisingly strong opening stop.","https://gv-images.viamichelin.com/images/michelin_guide/max/Img_27612.jpg?format=auto&width=1280"],
["Naples Cathedral (Duomo)",40.85257,14.25977,"The city's spiritual heart, layered over earlier Greek and Roman history.","30–45 min","What to do","Go inside. Look for the Chapel of San Gennaro, then ask about Santa Restituta and the early-Christian baptistery. If you have extra time, consider the rooftop route for city views.","https://www.revigorate.com/images/The-Cathedral-Assumption-of-Mary-campania.jpg"],
["Via dei Tribunali",40.85115,14.25706,"One of the ancient east–west streets through the historic centre.","30–45 min","What to do","Don't rush it. Walk slowly, look into courtyards and churches, and stop for a pizza fritta, cuoppo or espresso. Piazza San Gaetano is a good pause point.","https://upload.wikimedia.org/wikipedia/commons/c/ca/Napoli_-_Via_dei_Tribunali.jpg"],
["San Gregorio Armeno",40.85080,14.25781,"The famous street of Neapolitan nativity-scene artisans.","20–30 min","What to do","Walk the entire narrow lane and look closely at the tiny handmade figures. The workshops operate throughout the year; the street becomes especially crowded around the Christmas season.","https://www.tellonline.it/wp-content/uploads/2022/11/IMG-20221124-WA0000-1.jpg"],
["Spaccanapoli",40.84981,14.25972,"The famous straight line cutting through the ancient heart of Naples.","30–45 min","Why go","Spaccanapoli is essentially the lower decumanus of ancient Naples. The core monumental section from Gesù Nuovo toward Via Duomo is just over a kilometre.","https://gv-images.viamichelin.com/images/michelin_guide/max/Img_14454.jpg?format=auto&width=640"],
["Gesù Nuovo + Santa Chiara",40.84723,14.25151,"Two completely different churches facing the same lively square.","45–60 min","What to do","First inspect Gesù Nuovo's bizarre diamond-pointed stone façade, then cross to Santa Chiara. If you want one paid interior on the walk, choose Santa Chiara's colourful majolica cloister.","https://upload.wikimedia.org/wikipedia/commons/8/8f/Facade_of_Chiesa_del_Ges%C3%B9_Nuovo.jpg"],
["Via Toledo",40.83998,14.25254,"Naples' major shopping and pedestrian artery leading toward the monumental centre.","20–30 min","What to do","Use this as a change of atmosphere. Browse shops, grab a coffee or snack, and check out the famous Toledo Metro station if you like modern architecture.","https://cdn2.picryl.com/photo/2007/06/10/via-toledo-in-napoli-9d69be-1024.jpg"],
["Quartieri Spagnoli",40.83997,14.24711,"Dense 16th-century neighbourhood famous for narrow lanes, balconies and football culture.","30–45 min","Why go","This is where the walking tour becomes less about monuments and more about street life. The neighbourhood was built for Spanish garrisons and today is packed with shrines, laundry, scooters, bars and murals.","https://images.squarespace-cdn.com/content/v1/5876d8d6e3df28c4d83ae377/1712787634297-GVUKACRW91XOOD1ITC8D/napoli-naples-street-art-murals-194.jpg?format=2500w"],
["Galleria Umberto I",40.83842,14.24943,"Huge 19th-century iron-and-glass shopping gallery opposite the San Carlo theatre.","10–15 min","What to do","Walk underneath the central dome and look down at the floor mosaics. This is primarily a photography and architecture stop, so 10 minutes is enough.","https://www.partenopeculture.it/wp-content/uploads/2024/10/GALLERIA-UMBERTO-NAPOLI-PARTENOPECULTURE-1024x683.png"],
["Teatro San Carlo",40.83834,14.24925,"Historic royal opera house and one of Naples' grandest façades.","5–15 min","Why go","The theatre opened in 1737 and remains an active opera house. Even if you do not attend a performance, the exterior is directly on your route and takes only a few minutes.","https://ivasanat.com/blog/wp-content/uploads/2025/02/Teatro-di-San-Carlo-Napoli-Italya-1.jpg"],
["Piazza del Plebiscito",40.83583,14.24851,"Naples' enormous ceremonial square framed by the Royal Palace and Basilica of San Francesco di Paola.","15–25 min","What to do","Walk toward the centre and turn around for the full colonnade view. Take a few wide-angle photos, then sit on the edge of the square before continuing downhill.","https://www.101viajes.com/sites/default/files/piazza-plesbicito-napoles.jpg"],
["Santa Lucia / Castel dell'Ovo",40.82832,14.24760,"A waterfront neighbourhood and castle on a rocky island-like outcrop.","30–45 min","Why go","This is the biggest scenery change of the day: historic lanes give way to the Bay of Naples, boats and Vesuvius views. Check current access before planning to enter the castle.","https://www.gettyimages.com/"],
["Lungomare",40.82972,14.25008,"Naples' seafront promenade with open views across the bay.","30–60 min","What to do","Slow down. Walk along the water, take photos toward Vesuvius and use this section as your food/drink break. Sunset is particularly good here.","https://static.gamberorosso.it/2025/02/lungomare-napoli-1-1024x768.jpg"],
["Piazza Municipio",40.83834,14.25323,"A monumental square beside the port and a convenient finish with Metro access.","10 min","What to do","Use this as the decision point: finish here and take Metro Line 1, or continue exploring toward the port. If you still have energy, you can reverse part of the waterfront route.","https://aws-tiqets-cdn.imgix.net/images/content/cae70a5b37ee44fd9fd7277ed42cffd4.jpeg?auto=format%2Ccompress&fit=crop&q=70&s=034ac7e183c969392b179d2566c26195&w=600"]
].map((s,i)=>({name:s[0],lat:s[1],lon:s[2],desc:s[3],time:s[4],label:s[5],detail:s[6],image:s[7],i}));
const route=stops.map(s=>[s.lat,s.lon]);const map=L.map("map",{scrollWheelZoom:false}).setView([40.843,14.257],14);
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(map);
L.polyline(route,{color:"#dc2626",weight:5,opacity:.85}).addTo(map);
stops.forEach(s=>{const icon=L.divIcon({className:"",html:'<div style="background:#dc2626;color:white;border-radius:50%;width:30px;height:30px;text-align:center;padding-top:6px;font-weight:800;border:2px solid white">'+(s.i===0?"S":s.i)+'</div>',iconSize:[30,30],iconAnchor:[15,15]});L.marker([s.lat,s.lon],{icon}).addTo(map).bindPopup("<b>"+s.name+"</b><br>"+s.desc)});
map.fitBounds(L.latLngBounds(route),{padding:[25,25]});
const box=document.getElementById("stops");
stops.forEach(s=>{const g="https://www.google.com/maps/dir/?api=1&destination="+s.lat+","+s.lon+"&travelmode=walking";const image=s.image?'<img class="place-image" src="'+s.image+'" alt="'+s.name.replace(/^[^·]+· /,"")+'" loading="lazy">':"";const detail=s.detail?'<div class="detail"><b>'+s.label+':</b> '+s.detail+'</div>':"";box.insertAdjacentHTML("beforeend",'<article class="stop">'+image+'<div class="stop-body"><div><span class="num">'+(s.i===0?"S":s.i)+'</span><h2>'+s.name.replace(/^Start · /,"")+'</h2></div><p>'+s.desc+'</p>'+detail+'<small>'+s.time+'</small><div class="buttons"><a class="nav" href="'+g+'">Navigate</a><button class="nav maplink" onclick="map.setView(['+s.lat+','+s.lon+'],17)">Show on map</button></div></div></article>')});
document.getElementById("locate").onclick=()=>navigator.geolocation&&navigator.geolocation.getCurrentPosition(p=>{L.marker([p.coords.latitude,p.coords.longitude]).addTo(map).bindPopup("You are here").openPopup();map.setView([p.coords.latitude,p.coords.longitude],15)},()=>alert("Please allow location access."));